# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 16, 56, 25, 804679, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
